[package]
name = "templates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
insta = "1.9.0"
log = "0.4.14"
unicode-segmentation = "1.8.0"
walkdir = "2.3.2"
