# This toml file is only here to facilitate running 'gleam test'. This isn't a published gleam package.

name = "matcha"
version = "0.1.0"
licences = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.38.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
